name: elective3project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  http: ^1.2.1
  intl: ^0.20.2 # Often needed for date formatting
  sqflite: ^2.3.3
  path: ^1.9.0
  mailer: ^6.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7 # Or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

